[tool.poetry]
name = "beholder"
version = "0.1.0"
description = "Data observability"
authors = ["Jasper Groot"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.24.56"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
